### ISSUE TITLE
Facebook Scraping

### ISSUE THREAD

**Issue by MaximumPotato** [JustSxm/Deals-Scraper#1]
Is this currently working with Facebook? I have tried multiple different configurations and get hits from Kijiji, but nothing from Facebook. Here's the latest config file I attempted, it is very broad (searching for all "phone" posts in toronto in the last week) but gets no hits.

```
[DEFAULT]
keywords = phone
exclusions =
maxprice = 2000
minprice = 0
enablefacebook = True
enablekijiji = False
enableebay = False
enableamazon = False
enablelespacs = False
strictmode = True
facebookcityid = 110941395597405
; facebook use the id of the closest city to you for the searches, if not set it will return no ads
interval = 2
; every minutes the bot should scrape

[FACEBOOK]
date_listed = 7
; 0 = off, 1 = last 24h, 7 = days and 30 = 30 days
sortby = distance_ascend
; best_match, distance_ascend, creation_time_descend, price_ascend, price_descend
```

**Comment by JustSxm** [comment]
Hey there ! Does the branch v2 works for you? If it doesn't i'll look into it, but for me it seems to work. Perhaps you arent logged into facebook.

**Comment by LilChaveZz** [comment]
How do you log into facebook?
Or where do i write my account?

**Comment by JustSxm** [comment]
> How do you log into facebook?
> Or where do i write my account?

You simply log on facebook.com

**Comment by Night1099** [comment]
Im having the same problem, how does logging into facebook.com on your browser log you in on the scraper?

**Comment by JustSxm** [comment]
> Im having the same problem, how does logging into facebook.com on your browser log you in on the scraper?

With the "remember me" feature simply keep you logged in, that way the scraper doesn't need your credentials to work

**Comment by JustSxm** [comment]
I've just pushed the V2 to the master branch. Let me know by creating a new issue if you have any problem so I can help you with your issue
