### ISSUE TITLE
Price drop instead of title

### ISSUE THREAD

**Issue by rafaelribeiroo** [JustSxm/Deals-Scraper#4]
I would like to report an issue, when every ad has a price drop, price drop stay on value of title, like print below

![image](https://github.com/JustSxm/Deals-Scraper/assets/19275140/02e5e687-2ece-43f4-b3cf-62209f947567)

![image](https://github.com/JustSxm/Deals-Scraper/assets/19275140/1d695a48-da70-44a5-823e-0c5c1c521302)

**Comment by JustSxm** [comment]
Currently I dont have much time, but I'll look into fixing perhaps in January or this summer. Thanks!

**Comment by rafaelribeiroo** [comment]
I've fixed by myself, asap i'll send PR alright? TY for ur project
